# Generated by Django 3.2 on 2021-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
