# Generated by Django 3.2 on 2021-06-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210602_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='network.user'),
            preserve_default=False,
        ),
    ]
